apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_NAME: mydb
  DB_USER: myuser
  DB_PASS: mypassword
  DB_HOST: postgres-service
  JWT_SECRET: konik
  ADMIN_SECRET: batonik